# Generated by Django 4.0.6 on 2022-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('cur_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('charcode', models.CharField(max_length=6)),
                ('nominal', models.IntegerField()),
            ],
        ),
    ]
