# Generated by Django 4.0.6 on 2022-07-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='charcode',
            field=models.CharField(max_length=6, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='cur_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='nominal',
            field=models.IntegerField(verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.FloatField(verbose_name='Курс валюты'),
        ),
    ]
